#!/usr/bin/env bash

pushd contextminer
python setup.py install
popd

curl -L https://github.com/downloads/libevent/libevent/libevent-2.0.21-stable.tar.gz -o libevent-2.0.21-stable.tar.gz
tar xvzf libevent-2.0.21-stable.tar.gz
pushd libevent-2.0.21-stable
./configure
make
make install
popd

if [[ $(uname) -eq 'Darwin' ]]; then
    curl -L http://fastdl.mongodb.org/osx/mongodb-osx-x86_64-2.0.8.tgz -o mongodb-osx-x86_64-2.0.8.tgz 
    tar xvzf mongodb-osx-x86_64-2.0.8.tgz
    pushd mongodb-osx-x86_64-2.0.8 
        pushd bin
            cp * /usr/bin
        popd
    popd
elif [[ $(uname -m) -eq 'x86_64' ]]; then
    curl -L http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.0.8.tgz -o mongodb-linux-x86_64-2.0.8.tgz
    tar xvzf mongodb-linux-x86_64-2.0.8.tgz
    pushd mongodb-linux-x86_64-2.0.8
        pushd bin
            cp * /usr/bin
        popd
    popd
fi
